CC              = g++
#CFLAGS          = -std=c++17 -pg -O3 -Wall
#CFLAGS          = -std=c++17 -O3 -g -D_GLIBCXX_DEBUG
#CFLAGS          = -std=c++17 -g -O3 -Wall -D_GLIBCXX_DEBUG #-DNDEBUG 
#CFLAGS          = -std=c++17 -g -pg -O3 -Wall -DNDEBUG 
#CFLAGS          = -std=c++17 -g -O0 -fno-inline -Wall -D_GLIBCXX_DEBUG
#the following is for valgrind --leak-check=yes intsat c.lp
#CFLAGS          = -g -O0 -Wall

# for measuring time
CFLAGS          = -std=c++17 -O3 -Wall -static -DNDEBUG

# for checking correctness
#CFLAGS          = -std=c++17 -O3 -Wall -static 


# ifndef d
# CFLAGS += -DNDEBUG
# endif

SRCS =  main.cpp \
	Branching.cpp \
	Cleanup.cpp \
	ConflictAnalysis.cpp \
	ConstraintValue.cpp \
	CubeConquerAPI.cpp \
	DBAddition.cpp \
	MaxHeap.cpp \
	Model.cpp \
	Parser.cpp \
	PBConstraint.cpp \
	Propagate.cpp \
	Solver.cpp \
	WConstraint.cpp 

OBJS = $(addsuffix .o, $(basename $(SRCS) .cpp))

all: pbsat

pbsat: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o pbsat

%.o: %.cpp
	$(CC) $(CFLAGS) -c $*.cpp

clean:
	rm -f *.o intsatSolution.lp intsatSolution.pl pbsat

depend:
	makedepend -Y $(SRCS)


# DO NOT DELETE

main.o: Parser.h WConstraint.h Constraint.h Functions.h PBConstraint.h
main.o: Clause.h Model.h Reason.h MaxHeap.h Strategy.h Statistics.h Solver.h
main.o: OccurListVector.h
Branching.o: Solver.h PBConstraint.h Constraint.h Functions.h WConstraint.h
Branching.o: Clause.h Model.h Reason.h Strategy.h Statistics.h MaxHeap.h
Branching.o: OccurListVector.h
Cleanup.o: Solver.h PBConstraint.h Constraint.h Functions.h WConstraint.h
Cleanup.o: Clause.h Model.h Reason.h Strategy.h Statistics.h MaxHeap.h
Cleanup.o: OccurListVector.h
ConflictAnalysis.o: Solver.h PBConstraint.h Constraint.h Functions.h
ConflictAnalysis.o: WConstraint.h Clause.h Model.h Reason.h Strategy.h
ConflictAnalysis.o: Statistics.h MaxHeap.h OccurListVector.h
ConstraintValue.o: Solver.h PBConstraint.h Constraint.h Functions.h
ConstraintValue.o: WConstraint.h Clause.h Model.h Reason.h Strategy.h
ConstraintValue.o: Statistics.h MaxHeap.h OccurListVector.h
DBAddition.o: Solver.h PBConstraint.h Constraint.h Functions.h WConstraint.h
DBAddition.o: Clause.h Model.h Reason.h Strategy.h Statistics.h MaxHeap.h
DBAddition.o: OccurListVector.h
MaxHeap.o: MaxHeap.h
Model.o: Model.h Reason.h Clause.h WConstraint.h Constraint.h Functions.h
Model.o: PBConstraint.h
Parser.o: Parser.h WConstraint.h Constraint.h Functions.h PBConstraint.h
Parser.o: Clause.h Model.h Reason.h
PBConstraint.o: Functions.h PBConstraint.h Constraint.h WConstraint.h
PBConstraint.o: Clause.h Model.h Reason.h
Propagate.o: Solver.h PBConstraint.h Constraint.h Functions.h WConstraint.h
Propagate.o: Clause.h Model.h Reason.h Strategy.h Statistics.h MaxHeap.h
Propagate.o: OccurListVector.h
Solver.o: Solver.h PBConstraint.h Constraint.h Functions.h WConstraint.h
Solver.o: Clause.h Model.h Reason.h Strategy.h Statistics.h MaxHeap.h
Solver.o: OccurListVector.h
WConstraint.o: WConstraint.h Constraint.h Functions.h PBConstraint.h Clause.h
WConstraint.o: Model.h Reason.h
